In [1]:
import parser
import selenium.webdriver as webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import datetime

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get('https://adindex.ru/news/all.phtml')

In [4]:
mime_counter = 0

In [5]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
print('\n\n'.join([i.text for i in posts_cards]))

«Банки.ру» перешли на кириллицу в логотипе
Маркетинг 28.05.24 | 13:07

«Яндекс» представил нейросеть YandexGPT Lite третьего поколения
Digital 28.05.24 | 12:00

Короткие ролики стали самым быстрорастущим трендом во «ВКонтакте»
Исследования 28.05.24 | 10:52

Команда КВН «Русская дорога» создала одноименное шоу для СТС
Медиа 28.05.24 | 10:00

«Газпром-Медиа» представил первый мульткаст с использованием ИИ
Digital 28.05.24 | 09:40

В Госдуму внесен законопроект об уголовной ответственности за дипфейки
Право 28.05.24 | 09:28

«Балтика» выбыла из топ-10 самых популярных напитков
Тенденции 28.05.24 | 08:39

Онлайн-кинотеатр Wink начнет работать в странах СНГ
Digital 28.05.24 | 08:01

«Вкусно — и точка» откроет 50 новых заведений в этом году
Маркетинг 28.05.24 | 07:43

Театры получили рекордную выручку от зарубежных гастролей
Тенденции 28.05.24 | 07:31

Сабо Crocs оказались в мире Бикини Боттом
Креатив 27.05.24 | 19:11

Первый пациент Neuralink рассказал про жизнь с чипом в мозге
Digital 27.05.24 | 19:07

Брендлокатор. Подрядчиков ищут: «ВКонтакте», Тele2, Газпромбанк
Эккаунты 27.05.24 | 18:33

Дэвид Бекхэм стал лицом AliExpress
Маркетинг 27.05.24 | 17:54

TJ Collection выпустил ИИ-стилиста
Digital 27.05.24 | 17:41

Сфера маркетинга и рекламы показала самую высокую конкуренцию среди кандидатов
Исследования 27.05.24 | 16:04

In [16]:
for post_data in posts_cards:
    data = parser.get_post_data(post_data)
    print(data[0])
    print(data[1])
    
    print('\n\n')

                 date                   author  \
0 2024-05-27 19:11:00  Петрова Мария Сергеевна

                                   post_name post_tag post_id  \
0  Сабо Crocs оказались в мире Бикини Боттом  Креатив  322877

                                                link
0  https://adindex.ru/news/creative/2024/05/27/32...
2024-05-27 19:11:00



                 date                    author  \
0 2024-05-27 19:07:00  Борисова Ольга Борисовна

                                           post_name post_tag post_id  \
0  Первый пациент Neuralink рассказал про жизнь с...  Digital  322876

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 19:07:00



                 date                          author  \
0 2024-05-27 18:33:00  Григорьева Людмила Григорьевна

                                           post_name  post_tag post_id  \
0  Брендлокатор. Подрядчиков ищут: «ВКонтакте», Т...  Эккаунты  322874

                                                link
0  https://adindex.ru/news/ek/2024/05/27/322874.p...
2024-05-27 18:33:00



                 date                          author  \
0 2024-05-27 17:54:00  Григорьева Людмила Григорьевна

                            post_name   post_tag post_id  \
0  Дэвид Бекхэм стал лицом AliExpress  Маркетинг  322872

                                                link
0  https://adindex.ru/news/marketing/2024/05/27/3...
2024-05-27 17:54:00



                 date                author  \
0 2024-05-27 17:41:00  Иванов Иван Иванович

                            post_name post_tag post_id  \
0  TJ Collection выпустил ИИ-стилиста  Digital  322871

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 17:41:00



                 date                        author  \
0 2024-05-27 16:04:00  Данилова Светлана Викторовна

                                           post_name      post_tag post_id  \
0  Сфера маркетинга и рекламы показала самую высо...  Исследования  322868

                                                link
0  https://adindex.ru/news/researches/2024/05/27/...
2024-05-27 16:04:00



                 date                        author  \
0 2024-05-27 14:39:00  Данилова Светлана Викторовна

                                           post_name post_tag post_id  \
0  Бизнесмен Александр Соколовский снялся в мюзик...  Креатив  322864

                                                link
0  https://adindex.ru/news/creative/2024/05/27/32...
2024-05-27 14:39:00



                 date                          author  \
0 2024-05-27 12:50:00  Григорьева Людмила Григорьевна

                                           post_name post_tag post_id  \
0  Функция проверки фактов может появиться в «Тел...  Digital  322861

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 12:50:00



                 date                    author  \
0 2024-05-27 11:54:00  Борисова Ольга Борисовна

                                           post_name   post_tag post_id  \
0  РАЭК посчитала рынок продвижения на маркетплейсах  Тенденции  322859

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 11:54:00



                 date                        author  \
0 2024-05-27 10:06:00  Андреева Анастасия Андреевна

                                           post_name post_tag post_id  \
0  YouTube Music добавил функцию поиска песни по ...  Digital  322857

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 10:06:00



                 date                   author  \
0 2024-05-27 09:02:00  Петрова Мария Сергеевна

                                           post_name   post_tag post_id  \
0  Продажи театральных билетов в стране сократили...  Тенденции  322858

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 09:02:00



                 date                      author  \
0 2024-05-27 07:56:00  Сидоров Антон Владимирович

                                           post_name   post_tag post_id  \
0  Продажи игровых приставок выросли на 70% в пер...  Тенденции  322855

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:56:00



                 date                author  \
0 2024-05-27 07:48:00  Иванов Иван Иванович

                                           post_name   post_tag post_id  \
0  Россияне могли вложить в криптовалюту до $100 ...  Тенденции  322856

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:48:00



                 date                   author  \
0 2024-05-27 07:15:00  Петрова Мария Сергеевна

                                           post_name   post_tag post_id  \
0  Рынок доставки продуктов и товаров вырос на 55...  Тенденции  322854

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:15:00



                 date                  author  \
0 2024-05-27 07:08:00  Жукова Ирина Ильинична

                                           post_name   post_tag post_id  \
0  Более 50% опрошенных россиян сталкивались с во...  Тенденции  322853

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:08:00



                 date                          author  \
0 2024-05-24 18:46:00  Григорьева Людмила Григорьевна

                                           post_name   post_tag post_id  \
0  «Сказочный патруль» появился во «Вкусно — и то...  Маркетинг  322852

                                                link
0  https://adindex.ru/news/marketing/2024/05/24/3...
2024-05-24 18:46:00

In [15]:
next_button = driver.find_element(By.CLASS_NAME, 'mb-xl-0')
next_button.click()
mime_counter+=1

In [16]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')[mime_counter*16:]
print('\n\n'.join([i.text for i in posts_cards]))
print(len(posts_cards))

«Тинькофф» выпустил тактильную карту для людей с нарушениями зрения
Социальные проекты 14:58 | 23.05.24

S7 Airlines попыталась поймать лето
Креатив 12:59 | 23.05.24

«Яндекс Маркет» создал свой бренд кофе
Маркетинг 12:09 | 23.05.24

Выручка VK от онлайн-рекламы выросла почти на четверть в первом квартале
Digital 10:40 | 23.05.24

Телеведущая Марина Кравец названа бренд-амбассадором Ozon
Маркетинг 10:16 | 23.05.24

Траты россиян на новые автомобили сократились на 13% в апреле
Тенденции 09:33 | 23.05.24

Раньше других начинают зарабатывать представители поколения Х
Тенденции 08:00 | 23.05.24

Российский бизнес заинтересовался Бахрейном
Тенденции 07:33 | 23.05.24

Стоимость размещения рекламных постов в «Телеграме» выросла на треть
Тенденции 07:15 | 23.05.24

Бренд «Два мяча» и «Яндекс Музей» создали вдохновленные нейросетями кеды
Креатив 18:41 | 22.05.24

Google активировал искусственный интеллект для рекламодателей
Digital 18:06 | 22.05.24

ФАС завела дело против МТС из-за роста стоимости услуг
Право 15:55 | 22.05.24

Лидеров рейтинга RQ Index среди российских банков назвали в Москве
Пресс-релизы 15:40 | 22.05.24

Quiet Media запустила первую на российском рынке CPA-платформу на базе сегментов телеком-операторов
Пресс-релизы 15:30 | 22.05.24

Дмитрий Лазарев возглавил сеть «585*Золотой»
Кадры 14:32 | 22.05.24

Четверть опрошенных россиян надеются на возвращение иностранных брендов мебели
Исследования 13:31 | 22.05.24
16

In [26]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
print('\n\n'.join([i.text for i in posts_cards][16 * mime_counter:]))

«Тинькофф» выпустил тактильную карту для людей с нарушениями зрения
Социальные проекты 14:58 | 23.05.24

S7 Airlines попыталась поймать лето
Креатив 12:59 | 23.05.24

«Яндекс Маркет» создал свой бренд кофе
Маркетинг 12:09 | 23.05.24

Выручка VK от онлайн-рекламы выросла почти на четверть в первом квартале
Digital 10:40 | 23.05.24

Телеведущая Марина Кравец названа бренд-амбассадором Ozon
Маркетинг 10:16 | 23.05.24

Траты россиян на новые автомобили сократились на 13% в апреле
Тенденции 09:33 | 23.05.24

Раньше других начинают зарабатывать представители поколения Х
Тенденции 08:00 | 23.05.24

Российский бизнес заинтересовался Бахрейном
Тенденции 07:33 | 23.05.24

Стоимость размещения рекламных постов в «Телеграме» выросла на треть
Тенденции 07:15 | 23.05.24

Бренд «Два мяча» и «Яндекс Музей» создали вдохновленные нейросетями кеды
Креатив 18:41 | 22.05.24

Google активировал искусственный интеллект для рекламодателей
Digital 18:06 | 22.05.24

ФАС завела дело против МТС из-за роста стоимости услуг
Право 15:55 | 22.05.24

Лидеров рейтинга RQ Index среди российских банков назвали в Москве
Пресс-релизы 15:40 | 22.05.24

Quiet Media запустила первую на российском рынке CPA-платформу на базе сегментов телеком-операторов
Пресс-релизы 15:30 | 22.05.24

Дмитрий Лазарев возглавил сеть «585*Золотой»
Кадры 14:32 | 22.05.24

Четверть опрошенных россиян надеются на возвращение иностранных брендов мебели
Исследования 13:31 | 22.05.24

In [ ]:
Посещаемость торгцентров

In [53]:
mime_counter = 5

In [56]:
[i.text for i in posts_cards[mime_counter*16: ]]

['В России создан аналог игры Diablo — «Первый богатырь»\nDigital 09:51 | 20.05.24',
 'Большинство российских геймеров скачивают видеоигры в обход оплаты\nТенденции 07:54 | 20.05.24',
 '«Яндекс» допустил увеличение роботов-курьеров в два раза\nТенденции 07:43 | 20.05.24',
 'Ввоз в страну импортной воды почти восстановился за два года\nТенденции 07:33 | 20.05.24',
 'Посещаемость торгцентров сократилась на 2–3% в мае год к году\nТенденции 06:58 | 20.05.24',
 'Экс-участница Serebro призвала носить украшения Unode50 «не в свет, а когда тебе этого хочется»\nКреатив 18:40 | 17.05.24',
 'Тимоти Шаламе показал свою «многогранность» для Chanel\nКреатив 17:11 | 17.05.24',
 'Часовые тиктоки, доходы от рекламы в подкастах и новая должность в GroupM — обзор новостей в зарубежных СМИ\nDigital 16:37 | 17.05.24',
 'Yandex N.V. завершила первый этап сделки по продаже «Яндекса»\nМаркетинг 15:24 | 17.05.24',
 '«ВкусВилл» создал «дачественную» доставку\nКреатив 14:29 | 17.05.24',
 'Треть опрошенных российских компаний отказались от зарубежных сервисов видеосвязи\nИсследования 12:38 | 17.05.24',
 '«Авито Услуги» помогли «без стресса» выбрать мастера для ремонта техники и строительства\nКреатив 11:57 | 17.05.24',
 'Шеф-повар Food.ru приготовил еду в имитирующих нарушение зрения VR-очках\nСоциальные проекты 10:42 | 17.05.24',
 'Группа «Тинькофф» увеличила расходы на маркетинг и рекламу почти в 1,7 раза\nМаркетинг 08:59 | 17.05.24',
 'ТЦ полностью заместили площади покинувших страну брендов\nТенденции 07:58 | 17.05.24',
 '«Литрес» начал искать неофициальных переводчиков для работы\nТенденции 07:39 | 17.05.24']

In [57]:
today = datetime.datetime.today().date()
date_to = today
date_from = datetime.date(today.year, today.month, 20)
parsed_datas = pd.DataFrame()

for post_data in posts_cards[mime_counter * 16:]:
    parsed_data, post_date = parser.get_post_data(post_data)
    post_date = datetime.date(post_date.year, post_date.month, post_date.day)

    print( date_from, date_to, post_date )
    
    if post_date <= date_to and post_date >= date_from:
        print('Добавили еще строчку')
        parsed_datas = pd.concat([parsed_datas, parsed_data], ignore_index = True)

    else:
        print('Время превышаем')
        continue_search = False
        break

2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-17
Время превышаем

In [48]:
len(parsed_datas)

85

In [49]:
len(posts_cards)

96

In [58]:
parsed_datas

,date,author,post_name,post_tag,post_id,link
0,2024-05-20 09:51:00,Петрова Мария Сергеевна,В России создан аналог игры Diablo — «Первый б...,Digital,322695,https://adindex.ru/news/digital/2024/05/20/322...
1,2024-05-20 07:54:00,Сидоров Антон Владимирович,Большинство российских геймеров скачивают виде...,Тенденции,322694,https://adindex.ru/news/tendencies/2024/05/20/...
2,2024-05-20 07:43:00,Данилова Светлана Викторовна,«Яндекс» допустил увеличение роботов-курьеров ...,Тенденции,322693,https://adindex.ru/news/tendencies/2024/05/20/...
3,2024-05-20 07:33:00,Васильева Екатерина Васильевна,Ввоз в страну импортной воды почти восстановил...,Тенденции,322692,https://adindex.ru/news/tendencies/2024/05/20/...
4,2024-05-20 06:58:00,Жукова Ирина Ильинична,Посещаемость торгцентров сократилась на 2–3% в...,Тенденции,322691,https://adindex.ru/news/tendencies/2024/05/20/...

In [1]:
import parser
import selenium.webdriver as webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import datetime
import time

In [6]:
def parse_some_news(date_from : datetime.date, date_to : datetime.date, driver : webdriver.Chrome = None) -> pd.DataFrame:
    if not driver:
        driver = webdriver.Chrome()

    driver.get('https://adindex.ru/news/all.phtml')

    parsed_datas = pd.DataFrame()

    posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
    continue_search = True
    checked_rounds = 0
    # date = datetime.date(1970, 1, 1)

    while continue_search:
        # print([i.text for i in posts_cards])
        # print(date_from, date_to, date, date <= date_to, date >= date_from, date <= date_to and date >= date_from)
        # print(checked_rounds, '\n\n')


        posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
        # print([i.text for i in posts_cards])
        print(checked_rounds)

        for post_data in posts_cards[checked_rounds * 16 :]:
            parsed_data, post_date = parser.get_post_data(post_data)
            post_date = datetime.date(post_date.year, post_date.month, post_date.day)
            
            if post_date <= date_to and post_date >= date_from:
                parsed_datas = pd.concat([parsed_datas, parsed_data], ignore_index = True)

            else:
                continue_search = False
                break


        checked_rounds += 1


        next_button = driver.find_element(By.CLASS_NAME, 'mb-xl-0')
        next_button.click()

        time.sleep(1)

    driver.close()


    
    return(parsed_datas)

In [2]:
today = datetime.datetime.today().date()
date_from = datetime.date(today.year, today.month, 1)
date_to = today
driver = webdriver.Chrome()

In [3]:
result = parser.parse_some_news(date_from, date_to, driver)

In [5]:
result

,date,author,post_name,post_tag,post_id,link
0,2024-05-28 13:59:00,Андреева Анастасия Андреевна,Школьники выбрали профессии будущего в центре ...,Пресс-релизы,322895,https://adindex.ru/news/releases/2024/05/28/32...
1,2024-05-28 13:07:00,Васильева Екатерина Васильевна,Бренд «Банки.ру» перешел на кириллицу в логотипе,Маркетинг,322897,https://adindex.ru/news/marketing/2024/05/28/3...
2,2024-05-28 12:00:00,Андреева Анастасия Андреевна,«Яндекс» представил нейросеть YandexGPT Lite т...,Digital,322893,https://adindex.ru/news/digital/2024/05/28/322...
3,2024-05-28 10:52:00,Жукова Ирина Ильинична,Короткие ролики стали самым быстрорастущим тре...,Исследования,322890,https://adindex.ru/news/researches/2024/05/28/...
4,2024-05-28 10:00:00,Васильева Екатерина Васильевна,Команда КВН «Русская дорога» создала одноименн...,Медиа,322879,https://adindex.ru/news/media/2024/05/27/32287...
...,...,...,...,...,...,...
230,2024-05-02 09:10:00,Иванов Иван Иванович,В России перестали ставить оригинальные компле...,Тенденции,322398,https://adindex.ru/news/tendencies/2024/05/2/3...
231,2024-05-02 08:36:00,Борисова Ольга Борисовна,Каждый четвертый опрошенный россиянин подписан...,Тенденции,322395,https://adindex.ru/news/tendencies/2024/05/2/3...
232,2024-05-02 07:59:00,Данилова Светлана Викторовна,«М.Видео-Эльдорадо» увеличил предложение подер...,Тенденции,322394,https://adindex.ru/news/tendencies/2024/05/2/3...
233,2024-05-02 07:34:00,Данилова Светлана Викторовна,Роскомнадзор рекомендовал сократить сбор инфор...,Право,322393,https://adindex.ru/news/right/2024/05/2/322393...
234,2024-05-02 07:26:00,Егорова Надежда Андреевна,Рост ВВП страны замедлился по итогам марта,Тенденции,322392,https://adindex.ru/news/tendencies/2024/05/2/3...

In [6]:
len(result)

235

In [17]:
url = result.iloc[0].link

In [24]:
def get_data_from_url(url: str, date_from: datetime.date, date_to: datetime.date):
# def get_data_from_url(url: str, days_from : str = "yesterday", days_to : str = "today"):
    from statistics import median
    import requests

    params = {
        'ids': '22386646',
        # 'metrics': 'ym:s:visits,ym:s:pageviews,ym:s:users,ym:s:bounceRate,ym:s:pageDepth,ym:s:avgVisitDurationSeconds',
        # 'metrics': 'ym:s:pageviews',  # Метрика для просмотров страниц
        'metrics': 'ym:s:visits,ym:s:pageviews,ym:s:users,ym:s:bounceRate,ym:s:pageDepth,ym:s:avgVisitDurationSeconds',
        'dimensions': 'ym:s:refererDomain',  # Размерность для получения ссылок
        'date1': date_from,  # 7daysAgo за неделю, 30daysAgo за месяц, 365daysAgo за год
        'date2': date_to,
        'filters': f"ym:pv:URL=='{url}'"
    }

    dates_delta = abs((date_to - date_from).days)
    print(f'Дельта 1 - {dates_delta}')


    if dates_delta == 1:
        params['date1'] = f'yesterday'
        # print(f'{dates_delta}dayAgo')

    elif dates_delta > 1:
        params['date1'] = f'{dates_delta}daysAgo'

        # print(f'{dates_delta}daysAgo')

    
    dates_delta = abs((datetime.date.today() - date_to).days)
    print(f'Дельта 2 - {dates_delta}')


    if dates_delta == 0:
        params['date2'] = 'today'
    
    elif dates_delta == 1:
        params['date2'] = 'yesterday'
    
    elif dates_delta > 1:
        params['date2'] = f'{dates_delta}daysAgo'
    
    else:
        print('[!!!] Не долдны были здесь быть - трабла с датами.')



    
    # params['date2'] = 'today'


    

    api_url = 'https://api-metrika.yandex.net/stat/v1/data'


    headers = {
        # 'Authorization': 'OAuth y0_AgAAAABxT5u9AArjtwAAAADzHTIKv-VGe5uzTHqKqd3WWTTeIiZQ2WU',
        'Authorization': 'OAuth y0_AgAAAABxT5u9AArjtwAAAAEF76JkAACyj6gBOhNAkqhvgQqQ8cXYqh1BlA',
    }

    response = requests.get(api_url, headers=headers, params=params ).json()

    print(response)

    if not response['data']:
        return response, url


    page_metrics = []
    response_data = response['data']
    names = ['Посетители', "Читатели", "Уникальные пользователи", "% недочитываемости", "Глубина просмотра", "Ср. время на сайте (сек)"]


    for data in response_data:
        page_metrics.append(
            {
                'Сайт' : data['dimensions'][0]['name']
            }
        )

        for counter, metric_name in enumerate(names):
            page_metrics[-1].update(
                {
                    metric_name : data['metrics'][counter]
                }
            )
    out = [{}, {}, {'% недочитываемости' : [], 'Глубина просмотра' : [], "Ср. время на сайте (сек)"  : []}]

    restrict_keys = ['Сайт', '% недочитываемости', 'Глубина просмотра', "Ср. время на сайте (сек)"]


    for data in page_metrics:
        if 'telegram' not in data['Сайт']:
            if out[0]:
                out[0].update(
                    {
                        key : out[0][key] + data[key] for key in list(data.keys())[ : -3][1 :]
                    } 
                )
            
            else:
                for key in data:
                    if key != 'Сайт':
                        out[0][key] = data[key]


            for key in restrict_keys[1 :]:
                out[2][key].append(data[key])

        else:
            for key in data:
                if key != 'Сайт':
                    out[1][key] = round(data[key], 2)

    for key in out[2]:
        out[0][key] = median(out[2][key])

    del out[2]


    out[0] = {
        'Поисковые системы' : out[0]
    }

    out[1] = {
        'Telegram' : out[1]
    }

    totals = {}

    print(out, '\n')

    if out[1]['Telegram']:
        totals.update(
            {
                key : out[0]['Поисковые системы'][key] + out[1]['Telegram'][key]
                for key in list(out[0]['Поисковые системы'].keys())[ : 3]
            }
        )

        totals.update(
            {
                key : median([out[0]['Поисковые системы'][key], out[1]['Telegram'][key]])
                for key in list(out[0]['Поисковые системы'].keys())[3 :]
            }
        )

    else:
        totals.update(
            out[0]['Поисковые системы']
        )

    totals.update({'link' : url})
    # return response.json()
    return out, totals

In [25]:
get_data_from_url(url, date_from, date_to)

Дельта 1 - 1
Дельта 2 - 0
{'query': {'ids': [22386646], 'dimensions': ['ym:s:refererDomain'], 'metrics': ['ym:s:visits', 'ym:s:pageviews', 'ym:s:users', 'ym:s:bounceRate', 'ym:s:pageDepth', 'ym:s:avgVisitDurationSeconds'], 'sort': ['-ym:s:visits'], 'date1': '2024-05-27', 'date2': '2024-05-28', 'filters': "ym:pv:URL=='https://adindex.ru/news/marketing/2024/05/28/322897.phtml'", 'limit': 100, 'offset': 1, 'group': 'Week', 'auto_group_size': '1', 'attr_name': '', 'quantile': '50', 'offline_window': '21', 'attribution': 'LastSign', 'currency': 'RUB', 'funnel_window': '', 'adfox_event_id': '0', 'funnel_pattern': ''}, 'data': [{'dimensions': [{'name': 'adindex.ru', 'favicon': 'adindex.ru'}], 'metrics': [1.0, 21.0, 1.0, 0.0, 21.0, 5164.0]}, {'dimensions': [{'name': 'google.com', 'favicon': 'google.com'}], 'metrics': [1.0, 1.0, 1.0, 0.0, 1.0, 67.0]}, {'dimensions': [{'name': 'ya.ru', 'favicon': 'ya.ru'}], 'metrics': [1.0, 1.0, 1.0, 0.0, 1.0, 20.0]}], 'total_rows': 3, 'total_rows_rounded': False, 'sampled': False, 'contains_sensitive_data': False, 'sample_share': 1.0, 'sample_size': 20498, 'sample_space': 20498, 'data_lag': 0, 'totals': [3.0, 23.0, 3.0, 0.0, 7.66666667, 1750.33333333], 'min': [1.0, 1.0, 1.0, 0.0, 1.0, 20.0], 'max': [1.0, 21.0, 1.0, 0.0, 21.0, 5164.0]}
[{'Поисковые системы': {'Посетители': 3.0, 'Читатели': 23.0, 'Уникальные пользователи': 3.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 67.0}}, {'Telegram': {}}]

([{'Поисковые системы': {'Посетители': 3.0,
    'Читатели': 23.0,
    'Уникальные пользователи': 3.0,
    '% недочитываемости': 0.0,
    'Глубина просмотра': 1.0,
    'Ср. время на сайте (сек)': 67.0}},
  {'Telegram': {}}],
 {'Посетители': 3.0,
  'Читатели': 23.0,
  'Уникальные пользователи': 3.0,
  '% недочитываемости': 0.0,
  'Глубина просмотра': 1.0,
  'Ср. время на сайте (сек)': 67.0,
  'link': 'https://adindex.ru/news/marketing/2024/05/28/322897.phtml'})

In [28]:
if (datetime.date(today.year, today.month, 20) - today).days * -1 == 1:
    print(f'{(datetime.date(today.year, today.month, 20) - today).days * -1}dayAgo')

else:
    print(f'{(datetime.date(today.year, today.month, 20) - today).days * -1}daysAgo')

8daysAgo