In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Создайте экземпляр браузера
driver = webdriver.Chrome()

# Используйте execute_script для перехода на страницу асинхронно
driver.execute_script("window.location.href='https://adindex.ru/news/all.phtml';")
print('Сразу же идем дальше, не дожидаясь открытия страницы')

# Определите локатор для нужного элемента
element_locator = (By.ID, 'specific_element_id')

# Используйте WebDriverWait для ожидания появления элемента
try:
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located(element_locator)
    )
    # Элемент найден, можно работать с ним
    print("Элемент найден, выполняются действия...")
finally:
    # Закрыть вкладку
    driver.close()

# Закрыть браузер (опционально, если вы больше не собираетесь использовать браузер)
driver.quit()

Сразу же идем дальше, не дожидаясь открытия страницы

KeyboardInterrupt:

In [1]:
import parser
import selenium.webdriver as webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import datetime
import time

In [2]:
today = datetime.datetime.today().date()
date_from = datetime.date(today.year, today.month, 1)
date_to = today
driver = webdriver.Chrome()

In [3]:
result = parser.parse_some_news(date_from, date_to, driver, 0.5)

In [4]:
result

,date,author,post_name,post_tag,post_id,link
0,2024-05-29 11:38:00,Не указан,Экс-генеральный продюсер Ivi перешел в Premier,Кадры,322931,https://adindex.ru/news/hr/2024/05/29/322931.p...
1,2024-05-29 11:11:00,Не указан,Нейрообъявления от «Яндекса» появились в «Един...,Digital,322929,https://adindex.ru/news/digital/2024/05/29/322...
2,2024-05-29 09:55:00,Не указан,Vogue вновь снял Джиджи Хадид для своей олимпи...,Креатив,322921,https://adindex.ru/news/creative/2024/05/29/32...
3,2024-05-29 09:43:00,Не указан,Женщины и молодые люди стали чаще посещать каз...,Тенденции,322920,https://adindex.ru/news/tendencies/2024/05/29/...
4,2024-05-29 09:21:00,Не указан,Расходы россиян на машины с пробегом вновь пре...,Тенденции,322919,https://adindex.ru/news/tendencies/2024/05/29/...
...,...,...,...,...,...,...
246,2024-05-02 09:10:00,Не указан,В России перестали ставить оригинальные компле...,Тенденции,322398,https://adindex.ru/news/tendencies/2024/05/2/3...
247,2024-05-02 08:36:00,Не указан,Каждый четвертый опрошенный россиянин подписан...,Тенденции,322395,https://adindex.ru/news/tendencies/2024/05/2/3...
248,2024-05-02 07:59:00,Не указан,«М.Видео-Эльдорадо» увеличил предложение подер...,Тенденции,322394,https://adindex.ru/news/tendencies/2024/05/2/3...
249,2024-05-02 07:34:00,Не указан,Роскомнадзор рекомендовал сократить сбор инфор...,Право,322393,https://adindex.ru/news/right/2024/05/2/322393...
250,2024-05-02 07:26:00,Не указан,Рост ВВП страны замедлился по итогам марта,Тенденции,322392,https://adindex.ru/news/tendencies/2024/05/2/3...

In [7]:
len(result)

215

In [8]:
url = result.iloc[0].link

In [10]:
metrics = parser.get_data_from_url(url, date_from, date_to)

[{'Поисковые системы': {'Посетители': 4.0, 'Читатели': 37.0, 'Уникальные пользователи': 4.0, '% недочитываемости': 0.0, 'Глубина просмотра': 4.0, 'Ср. время на сайте (сек)': 186.0}}, {'Telegram': {}}]

In [46]:
result_metrics_united = pd.merge(result_copy, result_metrics)

In [49]:
result_metrics_united.to_csv('AdIndex_24_05-1_28_Metrics.csv')

In [38]:
pd.merge(result_copy, result_metrics)

,date,author,post_name,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек)
0,2024-05-28 16:25:00,Андреева Анастасия Андреевна,Число самозанятых на маркетплейсах сократилось...,Тенденции,322905,https://adindex.ru/news/tendencies/2024/05/28/...,4.0,37.0,4.0,0.00,4.000000,186.0
1,2024-05-28 16:06:00,Жукова Ирина Ильинична,«МегаФон» рассказал в рекламном ролике о беспл...,Пресс-релизы,322869,https://adindex.ru/news/releases/2024/05/27/32...,5.0,30.0,5.0,0.00,5.500000,262.0
2,2024-05-28 15:30:00,Данилова Светлана Викторовна,«Яндекс» сменил коммерческого директора,Кадры,322903,https://adindex.ru/news/hr/2024/05/28/322903.p...,45.0,128.0,45.0,3.57,1.998571,146.0

In [33]:
result_copy

Empty DataFrame
Columns: [date, author, post_name, post_tag, post_id, Посетители, Читатели, Уникальные пользователи, % недочитываемости, Глубина просмотра, Ср. время на сайте (сек), link]
Index: []

In [25]:
pd.DataFrame(row)

                                                           0
date                                     2024-05-28 16:25:00
author                          Андреева Анастасия Андреевна
post_name  Число самозанятых на маркетплейсах сократилось...
post_tag                                           Тенденции
post_id                                               322905
link       https://adindex.ru/news/tendencies/2024/05/28/...

In [21]:
pd.merge(pd.DataFrame(result.iloc[0]).T, pd.DataFrame.from_dict([metrics[-1]]))

,date,author,post_name,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек)
0,2024-05-28 16:25:00,Андреева Анастасия Андреевна,Число самозанятых на маркетплейсах сократилось...,Тенденции,322905,https://adindex.ru/news/tendencies/2024/05/28/...,4.0,37.0,4.0,0.0,4.0,186.0

In [14]:
metrics[-1]

{'Посетители': 4.0,
 'Читатели': 37.0,
 'Уникальные пользователи': 4.0,
 '% недочитываемости': 0.0,
 'Глубина просмотра': 4.0,
 'Ср. время на сайте (сек)': 186.0,
 'link': 'https://adindex.ru/news/tendencies/2024/05/28/322905.phtml'}