In [1]:
import pandas as pd
import plotly.express as px

In [10]:
df = pd.read_csv('AdIndex main news METRICS 2023-12-14.csv', index_col=0, parse_dates=True)

FileNotFoundError: [Errno 2] No such file or directory: 'AdIndex main news METRICS 2023-12-14.csv'

In [17]:
df

,date,author,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.00,16.500000,NaN
1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.000000,3.50,79.214286,NaN
2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.000000,1.25,14.750000,NaN
3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.000000,2.25,81.000000,NaN
4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.000000,1.00,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-12-04,Борисова Ольга Борисовна,Digital,317666,https://adindex.ru/news/digital/2023/12/4/3176...,3.0,3.0,3.0,25.000000,1.00,11.250000,NaN
95,2023-12-04,Данилова Светлана Викторовна,Маркетинг,317663,https://adindex.ru/news/marketing/2023/12/4/31...,2.0,2.0,2.0,50.000000,1.00,8.000000,NaN
96,2023-12-04,Жукова Ирина Ильинична,Право,317662,https://adindex.ru/news/right/2023/12/4/317662...,1.0,4.0,1.0,0.000000,4.00,8.000000,NaN
97,2023-12-04,Жукова Ирина Ильинична,Тенденции,317657,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,3.0,1.0,0.000000,3.00,1149.000000,NaN
98,2023-12-04,Андреева Анастасия Андреевна,Маркетинг,317656,https://adindex.ru/news/marketing/2023/12/4/31...,3.0,3.0,3.0,33.333333,1.00,10.333333,NaN

In [16]:
df['date'] = df['date'].apply(lambda x: pd.to_datetime(x))

In [19]:
df

,date,author,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.00,16.500000,NaN
1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.000000,3.50,79.214286,NaN
2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.000000,1.25,14.750000,NaN
3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.000000,2.25,81.000000,NaN
4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.000000,1.00,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-12-04,Борисова Ольга Борисовна,Digital,317666,https://adindex.ru/news/digital/2023/12/4/3176...,3.0,3.0,3.0,25.000000,1.00,11.250000,NaN
95,2023-12-04,Данилова Светлана Викторовна,Маркетинг,317663,https://adindex.ru/news/marketing/2023/12/4/31...,2.0,2.0,2.0,50.000000,1.00,8.000000,NaN
96,2023-12-04,Жукова Ирина Ильинична,Право,317662,https://adindex.ru/news/right/2023/12/4/317662...,1.0,4.0,1.0,0.000000,4.00,8.000000,NaN
97,2023-12-04,Жукова Ирина Ильинична,Тенденции,317657,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,3.0,1.0,0.000000,3.00,1149.000000,NaN
98,2023-12-04,Андреева Анастасия Андреевна,Маркетинг,317656,https://adindex.ru/news/marketing/2023/12/4/31...,3.0,3.0,3.0,33.333333,1.00,10.333333,NaN

In [20]:
px.line(df['post_id'])

---

In [15]:
# {'id': 'Model', 'name': 'Model'}


[{ 'id' : column, 'name' : column } for column in df.columns]

[{'id': 'date', 'name': 'date'},
 {'id': 'author', 'name': 'author'},
 {'id': 'post_tag', 'name': 'post_tag'},
 {'id': 'post_id', 'name': 'post_id'},
 {'id': 'link', 'name': 'link'},
 {'id': 'Посетители', 'name': 'Посетители'},
 {'id': 'Читатели', 'name': 'Читатели'},
 {'id': 'Уникальные пользователи', 'name': 'Уникальные пользователи'},
 {'id': '% недочитываемости', 'name': '% недочитываемости'},
 {'id': 'Глубина просмотра', 'name': 'Глубина просмотра'},
 {'id': 'Ср. время на сайте (сек)', 'name': 'Ср. время на сайте (сек)'},
 {'id': '0', 'name': '0'}]

In [22]:
for row in df.to_dict('records'):
    print(row)

    row.update({'editable' : True if row})

{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Тенденции', 'post_id': 318261, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318261.phtml', 'Посетители': 5.0, 'Читатели': 30.0, 'Уникальные пользователи': 5.0, '% недочитываемости': 0.0, 'Глубина просмотра': 2.0, 'Ср. время на сайте (сек)': 16.5, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Креатив', 'post_id': 318259, 'link': 'https://adindex.ru/news/creative/2023/12/13/318259.phtml', 'Посетители': 14.0, 'Читатели': 71.0, 'Уникальные пользователи': 14.0, '% недочитываемости': 0.0, 'Глубина просмотра': 3.5, 'Ср. время на сайте (сек)': 79.214285715, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Григорьева Людмила Григорьевна', 'post_tag': 'Тенденции', 'post_id': 318152, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318152.phtml', 'Посетители': 17.0, 'Читатели': 46.0, 'Уникальные пользователи': 17.0, '% недочитываемости': 25.0, 'Глубина просмотра': 1.25, 'Ср. время на сайте (сек)': 14.75, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Кадры', 'post_id': 318116, 'link': 'https://adindex.ru/news/hr/2023/12/13/318116.phtml', 'Посетители': 9.0, 'Читатели': 82.0, 'Уникальные пользователи': 9.0, '% недочитываемости': 0.0, 'Глубина просмотра': 2.25, 'Ср. время на сайте (сек)': 81.0, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Егорова Надежда Андреевна', 'post_tag': 'Социальные проекты', 'post_id': 318115, 'link': 'https://adindex.ru/news/social_advertising/2023/12/13/318115.phtml', 'Посетители': 5.0, 'Читатели': 8.0, 'Уникальные пользователи': 5.0, '% недочитываемости': 50.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 11.0, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Григорьева Людмила Григорьевна', 'post_tag': 'Агентства', 'post_id': 317957, 'link': 'https://adindex.ru/news/agencies/2023/12/11/317957.phtml', 'Посетители': 28.0, 'Читатели': 86.0, 'Уникальные пользователи': 27.0, '% недочитываемости': 3.5714285725, 'Глубина просмотра': 2.05, 'Ср. время на сайте (сек)': 114.8535714275, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Тенденции', 'post_id': 318095, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318095.phtml', 'Посетители': 11.0, 'Читатели': 120.0, 'Уникальные пользователи': 11.0, '% недочитываемости': 0.0, 'Глубина просмотра': 4.25, 'Ср. время на сайте (сек)': 181.25, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Право', 'post_id': 318092, 'link': 'https://adindex.ru/news/right/2023/12/13/318092.phtml', 'Посетители': 28.0, 'Читатели': 131.0, 'Уникальные пользователи': 27.0, '% недочитываемости': 0.0, 'Глубина просмотра': 2.2083333325, 'Ср. время на сайте (сек)': 79.0, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Григорьева Людмила Григорьевна', 'post_tag': 'Медиа', 'post_id': 318090, 'link': 'https://adindex.ru/news/media/2023/12/13/318090.phtml', 'Посетители': 25.0, 'Читатели': 124.0, 'Уникальные пользователи': 24.0, '% недочитываемости': 10.0, 'Глубина просмотра': 1.6166666675, 'Ср. время на сайте (сек)': 31.0666666675, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Тенденции', 'post_id': 318089, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318089.phtml', 'Посетители': 12.0, 'Читатели': 127.0, 'Уникальные пользователи': 12.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 19.0, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Маркетинг', 'post_id': 318088, 'link': 'https://adindex.ru/news/marketing/2023/12/13/318088.phtml', 'Посетители': 35.0, 'Читатели': 125.0, 'Уникальные пользователи': 35.0, '% недочитываемости': 20.0, 'Глубина просмотра': 1.70588235, 'Ср. время на сайте (сек)': 16.8, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Григорьева Людмила Григорьевна', 'post_tag': 'Медиа', 'post_id': 318086, 'link': 'https://adindex.ru/news/media/2023/12/13/318086.phtml', 'Посетители': 87.0, 'Читатели': 199.0, 'Уникальные пользователи': 86.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.2971698125, 'Ср. время на сайте (сек)': 28.3066037725, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Маркетинг', 'post_id': 318084, 'link': 'https://adindex.ru/news/marketing/2023/12/13/318084.phtml', 'Посетители': 14.0, 'Читатели': 89.0, 'Уникальные пользователи': 14.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 15.0, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Тенденции', 'post_id': 318083, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318083.phtml', 'Посетители': 34.0, 'Читатели': 150.0, 'Уникальные пользователи': 32.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.1666666650000002, 'Ср. время на сайте (сек)': 40.733333335, '0': nan}
{'date': Timestamp('2023-12-13 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Тенденции', 'post_id': 318082, 'link': 'https://adindex.ru/news/tendencies/2023/12/13/318082.phtml', 'Посетители': 12.0, 'Читатели': 71.0, 'Уникальные пользователи': 12.0, '% недочитываемости': 0.0, 'Глубина просмотра': 4.625, 'Ср. время на сайте (сек)': 244.6875, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Григорьева Людмила Григорьевна', 'post_tag': 'Право', 'post_id': 318081, 'link': 'https://adindex.ru/news/right/2023/12/12/318081.phtml', 'Посетители': 53.0, 'Читатели': 80.0, 'Уникальные пользователи': 52.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 16.33333333, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Креатив', 'post_id': 318080, 'link': 'https://adindex.ru/news/creative/2023/12/12/318080.phtml', 'Посетители': 31.0, 'Читатели': 104.0, 'Уникальные пользователи': 31.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.464285715, 'Ср. время на сайте (сек)': 45.75, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Право', 'post_id': 318079, 'link': 'https://adindex.ru/news/right/2023/12/12/318079.phtml', 'Посетители': 14.0, 'Читатели': 102.0, 'Уникальные пользователи': 14.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.875, 'Ср. время на сайте (сек)': 30.25, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Данилова Светлана Викторовна', 'post_tag': 'Право', 'post_id': 318076, 'link': 'https://adindex.ru/news/right/2023/12/12/318076.phtml', 'Посетители': 6.0, 'Читатели': 8.0, 'Уникальные пользователи': 6.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.1666666650000002, 'Ср. время на сайте (сек)': 33.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Социальные проекты', 'post_id': 318017, 'link': 'https://adindex.ru/news/social_advertising/2023/12/12/318017.phtml', 'Посетители': 12.0, 'Читатели': 66.0, 'Уникальные пользователи': 10.0, '% недочитываемости': 7.142857145, 'Глубина просмотра': 2.857142855, 'Ср. время на сайте (сек)': 192.535714285, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Егорова Надежда Андреевна', 'post_tag': 'Digital', 'post_id': 317999, 'link': 'https://adindex.ru/news/digital/2023/12/12/317999.phtml', 'Посетители': 21.0, 'Читатели': 100.0, 'Уникальные пользователи': 21.0, '% недочитываемости': 33.33333333, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 10.66666667, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Исследования', 'post_id': 317997, 'link': 'https://adindex.ru/news/researches/2023/12/12/317997.phtml', 'Посетители': 18.0, 'Читатели': 105.0, 'Уникальные пользователи': 16.0, '% недочитываемости': 0.0, 'Глубина просмотра': 7.11111111, 'Ср. время на сайте (сек)': 711.33333333, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Егорова Надежда Андреевна', 'post_tag': 'Исследования', 'post_id': 317995, 'link': 'https://adindex.ru/news/researches/2023/12/12/317995.phtml', 'Посетители': 43.0, 'Читатели': 115.0, 'Уникальные пользователи': 39.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.125, 'Ср. время на сайте (сек)': 18.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Маркетинг', 'post_id': 317993, 'link': 'https://adindex.ru/news/marketing/2023/12/12/317993.phtml', 'Посетители': 209.0, 'Читатели': 324.0, 'Уникальные пользователи': 205.0, '% недочитываемости': 9.09090909, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 16.5, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Исследования', 'post_id': 317965, 'link': 'https://adindex.ru/news/researches/2023/12/12/317965.phtml', 'Посетители': 7.0, 'Читатели': 52.0, 'Уникальные пользователи': 7.0, '% недочитываемости': 0.0, 'Глубина просмотра': 8.125, 'Ср. время на сайте (сек)': 396.75, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Социальные проекты', 'post_id': 317977, 'link': 'https://adindex.ru/news/social_advertising/2023/12/12/317977.phtml', 'Посетители': 2.0, 'Читатели': 3.0, 'Уникальные пользователи': 2.0, '% недочитываемости': 50.0, 'Глубина просмотра': 1.5, 'Ср. время на сайте (сек)': 54.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Сидоров Антон Владимирович', 'post_tag': 'Маркетинг', 'post_id': 317968, 'link': 'https://adindex.ru/news/marketing/2023/12/12/317968.phtml', 'Посетители': 937.0, 'Читатели': 1089.0, 'Уникальные пользователи': 882.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 15.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Право', 'post_id': 317964, 'link': 'https://adindex.ru/news/right/2023/12/12/317964.phtml', 'Посетители': 7.0, 'Читатели': 73.0, 'Уникальные пользователи': 7.0, '% недочитываемости': 29.166666665, 'Глубина просмотра': 10.583333335, 'Ср. время на сайте (сек)': 841.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Тенденции', 'post_id': 317963, 'link': 'https://adindex.ru/news/tendencies/2023/12/12/317963.phtml', 'Посетители': 5.0, 'Читатели': 5.0, 'Уникальные пользователи': 5.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 15.0, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Digital', 'post_id': 317961, 'link': 'https://adindex.ru/news/digital/2023/12/12/317961.phtml', 'Посетители': 20.0, 'Читатели': 49.0, 'Уникальные пользователи': 20.0, '% недочитываемости': 22.22222222, 'Глубина просмотра': 2.0, 'Ср. время на сайте (сек)': 60.11111111, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Тенденции', 'post_id': 317960, 'link': 'https://adindex.ru/news/tendencies/2023/12/12/317960.phtml', 'Посетители': 3.0, 'Читатели': 42.0, 'Уникальные пользователи': 3.0, '% недочитываемости': 0.0, 'Глубина просмотра': 10.75, 'Ср. время на сайте (сек)': 865.5, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Право', 'post_id': 317959, 'link': 'https://adindex.ru/news/right/2023/12/12/317959.phtml', 'Посетители': 51.0, 'Читатели': 63.0, 'Уникальные пользователи': 50.0, '% недочитываемости': 5.0, 'Глубина просмотра': 2.1, 'Ср. время на сайте (сек)': 116.05, '0': nan}
{'date': Timestamp('2023-12-12 00:00:00'), 'author': 'Данилова Светлана Викторовна', 'post_tag': 'Тенденции', 'post_id': 317958, 'link': 'https://adindex.ru/news/tendencies/2023/12/12/317958.phtml', 'Посетители': 9.0, 'Читатели': 22.0, 'Уникальные пользователи': 9.0, '% недочитываемости': 25.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 12.5, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Андреева Анастасия Андреевна', 'post_tag': 'Digital', 'post_id': 317948, 'link': 'https://adindex.ru/news/digital/2023/12/11/317948.phtml', 'Посетители': 7.0, 'Читатели': 46.0, 'Уникальные пользователи': 7.0, '% недочитываемости': 0.0, 'Глубина просмотра': 5.5, 'Ср. время на сайте (сек)': 868.333333335, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Креатив', 'post_id': 317943, 'link': 'https://adindex.ru/news/creative/2023/12/11/317943.phtml', 'Посетители': 119.0, 'Читатели': 205.0, 'Уникальные пользователи': 110.0, '% недочитываемости': 50.0, 'Глубина просмотра': 1.3076923075, 'Ср. время на сайте (сек)': 18.35989011, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Эккаунты', 'post_id': 317936, 'link': 'https://adindex.ru/news/ek/2023/12/11/317936.phtml', 'Посетители': 4.0, 'Читатели': 9.0, 'Уникальные пользователи': 4.0, '% недочитываемости': 0.0, 'Глубина просмотра': 2.0, 'Ср. время на сайте (сек)': 873.5, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Креатив', 'post_id': 317931, 'link': 'https://adindex.ru/news/creative/2023/12/11/317931.phtml', 'Посетители': 13.0, 'Читатели': 95.0, 'Уникальные пользователи': 13.0, '% недочитываемости': 0.0, 'Глубина просмотра': 6.8, 'Ср. время на сайте (сек)': 476.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Жукова Ирина Ильинична', 'post_tag': 'Маркетинг', 'post_id': 317929, 'link': 'https://adindex.ru/news/marketing/2023/12/11/317929.phtml', 'Посетители': 4.0, 'Читатели': 34.0, 'Уникальные пользователи': 4.0, '% недочитываемости': 0.0, 'Глубина просмотра': 6.0, 'Ср. время на сайте (сек)': 811.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Андреева Анастасия Андреевна', 'post_tag': 'Маркетинг', 'post_id': 317883, 'link': 'https://adindex.ru/news/marketing/2023/12/11/317883.phtml', 'Посетители': 10.0, 'Читатели': 60.0, 'Уникальные пользователи': 10.0, '% недочитываемости': 0.0, 'Глубина просмотра': 5.5, 'Ср. время на сайте (сек)': 959.33333333, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Медиа', 'post_id': 317886, 'link': 'https://adindex.ru/news/media/2023/12/11/317886.phtml', 'Посетители': 237.0, 'Читатели': 259.0, 'Уникальные пользователи': 234.0, '% недочитываемости': 16.66666667, 'Глубина просмотра': 1.14285714, 'Ср. время на сайте (сек)': 36.31666667, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Сидоров Антон Владимирович', 'post_tag': 'Креатив', 'post_id': 317884, 'link': 'https://adindex.ru/news/creative/2023/12/11/317884.phtml', 'Посетители': 13.0, 'Читатели': 89.0, 'Уникальные пользователи': 13.0, '% недочитываемости': 0.0, 'Глубина просмотра': 9.0, 'Ср. время на сайте (сек)': 331.8, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Сидоров Антон Владимирович', 'post_tag': 'Тенденции', 'post_id': 317882, 'link': 'https://adindex.ru/news/tendencies/2023/12/11/317882.phtml', 'Посетители': 1.0, 'Читатели': 25.0, 'Уникальные пользователи': 1.0, '% недочитываемости': 0.0, 'Глубина просмотра': 25.0, 'Ср. время на сайте (сек)': 1289.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Данилова Светлана Викторовна', 'post_tag': 'Пресс-релизы', 'post_id': 317881, 'link': 'https://adindex.ru/news/releases/2023/12/11/317881.phtml', 'Посетители': 10.0, 'Читатели': 18.0, 'Уникальные пользователи': 10.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 171.5, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Данилова Светлана Викторовна', 'post_tag': 'Тенденции', 'post_id': 317879, 'link': 'https://adindex.ru/news/tendencies/2023/12/11/317879.phtml', 'Посетители': 1.0, 'Читатели': 25.0, 'Уникальные пользователи': 1.0, '% недочитываемости': 0.0, 'Глубина просмотра': 25.0, 'Ср. время на сайте (сек)': 1289.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Тенденции', 'post_id': 317878, 'link': 'https://adindex.ru/news/tendencies/2023/12/11/317878.phtml', 'Посетители': 1.0, 'Читатели': 1.0, 'Уникальные пользователи': 1.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 16.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Васильева Екатерина Васильевна', 'post_tag': 'Тенденции', 'post_id': 317877, 'link': 'https://adindex.ru/news/tendencies/2023/12/11/317877.phtml', 'Посетители': 1.0, 'Читатели': 16.0, 'Уникальные пользователи': 1.0, '% недочитываемости': 0.0, 'Глубина просмотра': 16.0, 'Ср. время на сайте (сек)': 2141.0, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Борисова Ольга Борисовна', 'post_tag': 'Тенденции', 'post_id': 317875, 'link': 'https://adindex.ru/news/tendencies/2023/12/11/317875.phtml', 'Посетители': 6.0, 'Читатели': 25.0, 'Уникальные пользователи': 6.0, '% недочитываемости': 0.0, 'Глубина просмотра': 2.25, 'Ср. время на сайте (сек)': 31.5, '0': nan}
{'date': Timestamp('2023-12-11 00:00:00'), 'author': 'Егорова Надежда Андреевна', 'post_tag': 'Digital', 'post_id': 317874, 'link': 'https://adindex.ru/news/digital/2023/12/11/317874.phtml', 'Посетители': 8.0, 'Читатели': 37.0, 'Уникальные пользователи': 7.0, '% недочитываемости': 7.142857145, 'Глубина просмотра': 15.07142857, 'Ср. время на сайте (сек)': 2052.5, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Тенденции', 'post_id': 317832, 'link': 'https://adindex.ru/news/tendencies/2023/12/8/317832.phtml', 'Посетители': 2.0, 'Читатели': 19.0, 'Уникальные пользователи': 2.0, '% недочитываемости': 0.0, 'Глубина просмотра': 9.5, 'Ср. время на сайте (сек)': 1092.0, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Эккаунты', 'post_id': 317827, 'link': 'https://adindex.ru/news/ek/2023/12/8/317827.phtml', 'Посетители': 2.0, 'Читатели': 3.0, 'Уникальные пользователи': 2.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.5, 'Ср. время на сайте (сек)': 342.5, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Иванов Иван Иванович', 'post_tag': 'Креатив', 'post_id': 317825, 'link': 'https://adindex.ru/news/creative/2023/12/8/317825.phtml', 'Посетители': 5.0, 'Читатели': 21.0, 'Уникальные пользователи': 5.0, '% недочитываемости': 41.666666665, 'Глубина просмотра': 3.75, 'Ср. время на сайте (сек)': 362.333333335, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Данилова Светлана Викторовна', 'post_tag': 'Медиа', 'post_id': 317821, 'link': 'https://adindex.ru/news/media/2023/12/8/317821.phtml', 'Посетители': 12.0, 'Читатели': 12.0, 'Уникальные пользователи': 12.0, '% недочитываемости': 40.0, 'Глубина просмотра': 1.0, 'Ср. время на сайте (сек)': 11.2, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Петрова Мария Сергеевна', 'post_tag': 'Право', 'post_id': 317818, 'link': 'https://adindex.ru/news/right/2023/12/8/317818.phtml', 'Посетители': 8.0, 'Читатели': 15.0, 'Уникальные пользователи': 8.0, '% недочитываемости': 0.0, 'Глубина просмотра': 1.25, 'Ср. время на сайте (сек)': 19.75, '0': nan}
{'date': Timestamp('2023-12-08 00:00:00'), 'author': 'Сидоров Антон Владимирович', 'post_tag': 'Право', 'post_id': 317810, 'link': 'https://adindex.ru/news/right/2023/12/8/317810.phtml', 'Посетители': 1.0, 'Читатели': 7.0, 'Уникальные пользователи': 1.0, '% недочитываемости': 0.0, 'Глубина просмотра': 7.0, 'Ср. время на сайте (сек)': 331.0, '0': nan}